// Code generated by go-swagger; DO NOT EDIT.

package openstack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/syseleven/terraform-provider-metakube/go-metakube/models"
)

// ListOpenstackImagesNoCredentialsReader is a Reader for the ListOpenstackImagesNoCredentials structure.
type ListOpenstackImagesNoCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOpenstackImagesNoCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOpenstackImagesNoCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListOpenstackImagesNoCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListOpenstackImagesNoCredentialsOK creates a ListOpenstackImagesNoCredentialsOK with default headers values
func NewListOpenstackImagesNoCredentialsOK() *ListOpenstackImagesNoCredentialsOK {
	return &ListOpenstackImagesNoCredentialsOK{}
}

/*ListOpenstackImagesNoCredentialsOK handles this case with default header values.

Image
*/
type ListOpenstackImagesNoCredentialsOK struct {
	Payload []*models.Image
}

func (o *ListOpenstackImagesNoCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/providers/openstack/images][%d] listOpenstackImagesNoCredentialsOK  %+v", 200, o.Payload)
}

func (o *ListOpenstackImagesNoCredentialsOK) GetPayload() []*models.Image {
	return o.Payload
}

func (o *ListOpenstackImagesNoCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOpenstackImagesNoCredentialsDefault creates a ListOpenstackImagesNoCredentialsDefault with default headers values
func NewListOpenstackImagesNoCredentialsDefault(code int) *ListOpenstackImagesNoCredentialsDefault {
	return &ListOpenstackImagesNoCredentialsDefault{
		_statusCode: code,
	}
}

/*ListOpenstackImagesNoCredentialsDefault handles this case with default header values.

errorResponse
*/
type ListOpenstackImagesNoCredentialsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list openstack images no credentials default response
func (o *ListOpenstackImagesNoCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *ListOpenstackImagesNoCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/providers/openstack/images][%d] listOpenstackImagesNoCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ListOpenstackImagesNoCredentialsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListOpenstackImagesNoCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
