// Code generated by go-swagger; DO NOT EDIT.

package openstack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/syseleven/terraform-provider-metakube/go-metakube/models"
)

// ListOpenstackQuotaLimitsNoCredentialsReader is a Reader for the ListOpenstackQuotaLimitsNoCredentials structure.
type ListOpenstackQuotaLimitsNoCredentialsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListOpenstackQuotaLimitsNoCredentialsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListOpenstackQuotaLimitsNoCredentialsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewListOpenstackQuotaLimitsNoCredentialsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewListOpenstackQuotaLimitsNoCredentialsOK creates a ListOpenstackQuotaLimitsNoCredentialsOK with default headers values
func NewListOpenstackQuotaLimitsNoCredentialsOK() *ListOpenstackQuotaLimitsNoCredentialsOK {
	return &ListOpenstackQuotaLimitsNoCredentialsOK{}
}

/*ListOpenstackQuotaLimitsNoCredentialsOK handles this case with default header values.

Quotas
*/
type ListOpenstackQuotaLimitsNoCredentialsOK struct {
	Payload *models.Quotas
}

func (o *ListOpenstackQuotaLimitsNoCredentialsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/providers/openstack/quotalimits][%d] listOpenstackQuotaLimitsNoCredentialsOK  %+v", 200, o.Payload)
}

func (o *ListOpenstackQuotaLimitsNoCredentialsOK) GetPayload() *models.Quotas {
	return o.Payload
}

func (o *ListOpenstackQuotaLimitsNoCredentialsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Quotas)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListOpenstackQuotaLimitsNoCredentialsDefault creates a ListOpenstackQuotaLimitsNoCredentialsDefault with default headers values
func NewListOpenstackQuotaLimitsNoCredentialsDefault(code int) *ListOpenstackQuotaLimitsNoCredentialsDefault {
	return &ListOpenstackQuotaLimitsNoCredentialsDefault{
		_statusCode: code,
	}
}

/*ListOpenstackQuotaLimitsNoCredentialsDefault handles this case with default header values.

errorResponse
*/
type ListOpenstackQuotaLimitsNoCredentialsDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the list openstack quota limits no credentials default response
func (o *ListOpenstackQuotaLimitsNoCredentialsDefault) Code() int {
	return o._statusCode
}

func (o *ListOpenstackQuotaLimitsNoCredentialsDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/providers/openstack/quotalimits][%d] listOpenstackQuotaLimitsNoCredentials default  %+v", o._statusCode, o.Payload)
}

func (o *ListOpenstackQuotaLimitsNoCredentialsDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *ListOpenstackQuotaLimitsNoCredentialsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
