// Code generated by go-swagger; DO NOT EDIT.

package openstack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListOpenstackQuotaLimitsParams creates a new ListOpenstackQuotaLimitsParams object
// with the default values initialized.
func NewListOpenstackQuotaLimitsParams() *ListOpenstackQuotaLimitsParams {

	return &ListOpenstackQuotaLimitsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListOpenstackQuotaLimitsParamsWithTimeout creates a new ListOpenstackQuotaLimitsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListOpenstackQuotaLimitsParamsWithTimeout(timeout time.Duration) *ListOpenstackQuotaLimitsParams {

	return &ListOpenstackQuotaLimitsParams{

		timeout: timeout,
	}
}

// NewListOpenstackQuotaLimitsParamsWithContext creates a new ListOpenstackQuotaLimitsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListOpenstackQuotaLimitsParamsWithContext(ctx context.Context) *ListOpenstackQuotaLimitsParams {

	return &ListOpenstackQuotaLimitsParams{

		Context: ctx,
	}
}

// NewListOpenstackQuotaLimitsParamsWithHTTPClient creates a new ListOpenstackQuotaLimitsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListOpenstackQuotaLimitsParamsWithHTTPClient(client *http.Client) *ListOpenstackQuotaLimitsParams {

	return &ListOpenstackQuotaLimitsParams{
		HTTPClient: client,
	}
}

/*ListOpenstackQuotaLimitsParams contains all the parameters to send to the API endpoint
for the list openstack quota limits operation typically these are written to a http.Request
*/
type ListOpenstackQuotaLimitsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list openstack quota limits params
func (o *ListOpenstackQuotaLimitsParams) WithTimeout(timeout time.Duration) *ListOpenstackQuotaLimitsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list openstack quota limits params
func (o *ListOpenstackQuotaLimitsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list openstack quota limits params
func (o *ListOpenstackQuotaLimitsParams) WithContext(ctx context.Context) *ListOpenstackQuotaLimitsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list openstack quota limits params
func (o *ListOpenstackQuotaLimitsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list openstack quota limits params
func (o *ListOpenstackQuotaLimitsParams) WithHTTPClient(client *http.Client) *ListOpenstackQuotaLimitsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list openstack quota limits params
func (o *ListOpenstackQuotaLimitsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListOpenstackQuotaLimitsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
