// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/syseleven/terraform-provider-metakube/go-metakube/models"
)

// NewCreateNodeDeploymentRequestParams creates a new CreateNodeDeploymentRequestParams object
// with the default values initialized.
func NewCreateNodeDeploymentRequestParams() *CreateNodeDeploymentRequestParams {
	var ()
	return &CreateNodeDeploymentRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateNodeDeploymentRequestParamsWithTimeout creates a new CreateNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateNodeDeploymentRequestParamsWithTimeout(timeout time.Duration) *CreateNodeDeploymentRequestParams {
	var ()
	return &CreateNodeDeploymentRequestParams{

		timeout: timeout,
	}
}

// NewCreateNodeDeploymentRequestParamsWithContext creates a new CreateNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateNodeDeploymentRequestParamsWithContext(ctx context.Context) *CreateNodeDeploymentRequestParams {
	var ()
	return &CreateNodeDeploymentRequestParams{

		Context: ctx,
	}
}

// NewCreateNodeDeploymentRequestParamsWithHTTPClient creates a new CreateNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateNodeDeploymentRequestParamsWithHTTPClient(client *http.Client) *CreateNodeDeploymentRequestParams {
	var ()
	return &CreateNodeDeploymentRequestParams{
		HTTPClient: client,
	}
}

/*CreateNodeDeploymentRequestParams contains all the parameters to send to the API endpoint
for the create node deployment request operation typically these are written to a http.Request
*/
type CreateNodeDeploymentRequestParams struct {

	/*Body*/
	Body *models.NodeDeploymentRequest
	/*ClusterID*/
	ClusterID string
	/*Dc*/
	DC string
	/*ProjectID*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) WithTimeout(timeout time.Duration) *CreateNodeDeploymentRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) WithContext(ctx context.Context) *CreateNodeDeploymentRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) WithHTTPClient(client *http.Client) *CreateNodeDeploymentRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) WithBody(body *models.NodeDeploymentRequest) *CreateNodeDeploymentRequestParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) SetBody(body *models.NodeDeploymentRequest) {
	o.Body = body
}

// WithClusterID adds the clusterID to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) WithClusterID(clusterID string) *CreateNodeDeploymentRequestParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithDC adds the dc to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) WithDC(dc string) *CreateNodeDeploymentRequestParams {
	o.SetDC(dc)
	return o
}

// SetDC adds the dc to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) SetDC(dc string) {
	o.DC = dc
}

// WithProjectID adds the projectID to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) WithProjectID(projectID string) *CreateNodeDeploymentRequestParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the create node deployment request params
func (o *CreateNodeDeploymentRequestParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateNodeDeploymentRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param dc
	if err := r.SetPathParam("dc", o.DC); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
