// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/syseleven/terraform-provider-metakube/go-metakube/models"
)

// DeleteNodeDeploymentRequestReader is a Reader for the DeleteNodeDeploymentRequest structure.
type DeleteNodeDeploymentRequestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNodeDeploymentRequestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteNodeDeploymentRequestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteNodeDeploymentRequestUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteNodeDeploymentRequestForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewDeleteNodeDeploymentRequestDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteNodeDeploymentRequestOK creates a DeleteNodeDeploymentRequestOK with default headers values
func NewDeleteNodeDeploymentRequestOK() *DeleteNodeDeploymentRequestOK {
	return &DeleteNodeDeploymentRequestOK{}
}

/*DeleteNodeDeploymentRequestOK handles this case with default header values.

EmptyResponse is a empty response
*/
type DeleteNodeDeploymentRequestOK struct {
}

func (o *DeleteNodeDeploymentRequestOK) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/ndrequests/{ndrequest_id}][%d] deleteNodeDeploymentRequestOK ", 200)
}

func (o *DeleteNodeDeploymentRequestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNodeDeploymentRequestUnauthorized creates a DeleteNodeDeploymentRequestUnauthorized with default headers values
func NewDeleteNodeDeploymentRequestUnauthorized() *DeleteNodeDeploymentRequestUnauthorized {
	return &DeleteNodeDeploymentRequestUnauthorized{}
}

/*DeleteNodeDeploymentRequestUnauthorized handles this case with default header values.

EmptyResponse is a empty response
*/
type DeleteNodeDeploymentRequestUnauthorized struct {
}

func (o *DeleteNodeDeploymentRequestUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/ndrequests/{ndrequest_id}][%d] deleteNodeDeploymentRequestUnauthorized ", 401)
}

func (o *DeleteNodeDeploymentRequestUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNodeDeploymentRequestForbidden creates a DeleteNodeDeploymentRequestForbidden with default headers values
func NewDeleteNodeDeploymentRequestForbidden() *DeleteNodeDeploymentRequestForbidden {
	return &DeleteNodeDeploymentRequestForbidden{}
}

/*DeleteNodeDeploymentRequestForbidden handles this case with default header values.

EmptyResponse is a empty response
*/
type DeleteNodeDeploymentRequestForbidden struct {
}

func (o *DeleteNodeDeploymentRequestForbidden) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/ndrequests/{ndrequest_id}][%d] deleteNodeDeploymentRequestForbidden ", 403)
}

func (o *DeleteNodeDeploymentRequestForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNodeDeploymentRequestDefault creates a DeleteNodeDeploymentRequestDefault with default headers values
func NewDeleteNodeDeploymentRequestDefault(code int) *DeleteNodeDeploymentRequestDefault {
	return &DeleteNodeDeploymentRequestDefault{
		_statusCode: code,
	}
}

/*DeleteNodeDeploymentRequestDefault handles this case with default header values.

errorResponse
*/
type DeleteNodeDeploymentRequestDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the delete node deployment request default response
func (o *DeleteNodeDeploymentRequestDefault) Code() int {
	return o._statusCode
}

func (o *DeleteNodeDeploymentRequestDefault) Error() string {
	return fmt.Sprintf("[DELETE /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/ndrequests/{ndrequest_id}][%d] deleteNodeDeploymentRequest default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteNodeDeploymentRequestDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *DeleteNodeDeploymentRequestDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
