// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetNodeDeploymentRequestParams creates a new GetNodeDeploymentRequestParams object
// with the default values initialized.
func NewGetNodeDeploymentRequestParams() *GetNodeDeploymentRequestParams {
	var ()
	return &GetNodeDeploymentRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNodeDeploymentRequestParamsWithTimeout creates a new GetNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNodeDeploymentRequestParamsWithTimeout(timeout time.Duration) *GetNodeDeploymentRequestParams {
	var ()
	return &GetNodeDeploymentRequestParams{

		timeout: timeout,
	}
}

// NewGetNodeDeploymentRequestParamsWithContext creates a new GetNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNodeDeploymentRequestParamsWithContext(ctx context.Context) *GetNodeDeploymentRequestParams {
	var ()
	return &GetNodeDeploymentRequestParams{

		Context: ctx,
	}
}

// NewGetNodeDeploymentRequestParamsWithHTTPClient creates a new GetNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNodeDeploymentRequestParamsWithHTTPClient(client *http.Client) *GetNodeDeploymentRequestParams {
	var ()
	return &GetNodeDeploymentRequestParams{
		HTTPClient: client,
	}
}

/*GetNodeDeploymentRequestParams contains all the parameters to send to the API endpoint
for the get node deployment request operation typically these are written to a http.Request
*/
type GetNodeDeploymentRequestParams struct {

	/*ClusterID*/
	ClusterID string
	/*Dc*/
	DC string
	/*NdrequestID*/
	NdrName string
	/*ProjectID*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) WithTimeout(timeout time.Duration) *GetNodeDeploymentRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) WithContext(ctx context.Context) *GetNodeDeploymentRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) WithHTTPClient(client *http.Client) *GetNodeDeploymentRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterID adds the clusterID to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) WithClusterID(clusterID string) *GetNodeDeploymentRequestParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithDC adds the dc to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) WithDC(dc string) *GetNodeDeploymentRequestParams {
	o.SetDC(dc)
	return o
}

// SetDC adds the dc to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) SetDC(dc string) {
	o.DC = dc
}

// WithNdrName adds the ndrequestID to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) WithNdrName(ndrequestID string) *GetNodeDeploymentRequestParams {
	o.SetNdrName(ndrequestID)
	return o
}

// SetNdrName adds the ndrequestId to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) SetNdrName(ndrequestID string) {
	o.NdrName = ndrequestID
}

// WithProjectID adds the projectID to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) WithProjectID(projectID string) *GetNodeDeploymentRequestParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the get node deployment request params
func (o *GetNodeDeploymentRequestParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *GetNodeDeploymentRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param dc
	if err := r.SetPathParam("dc", o.DC); err != nil {
		return err
	}

	// path param ndrequest_id
	if err := r.SetPathParam("ndrequest_id", o.NdrName); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
