// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/syseleven/terraform-provider-metakube/go-metakube/models"
)

// GetKubeLoginClusterKubeconfigReader is a Reader for the GetKubeLoginClusterKubeconfig structure.
type GetKubeLoginClusterKubeconfigReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetKubeLoginClusterKubeconfigReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetKubeLoginClusterKubeconfigOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetKubeLoginClusterKubeconfigUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetKubeLoginClusterKubeconfigForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewGetKubeLoginClusterKubeconfigDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetKubeLoginClusterKubeconfigOK creates a GetKubeLoginClusterKubeconfigOK with default headers values
func NewGetKubeLoginClusterKubeconfigOK() *GetKubeLoginClusterKubeconfigOK {
	return &GetKubeLoginClusterKubeconfigOK{}
}

/*GetKubeLoginClusterKubeconfigOK handles this case with default header values.

Kubeconfig is a clusters kubeconfig
*/
type GetKubeLoginClusterKubeconfigOK struct {
	Payload []uint8
}

func (o *GetKubeLoginClusterKubeconfigOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/kubeloginkubeconfig][%d] getKubeLoginClusterKubeconfigOK  %+v", 200, o.Payload)
}

func (o *GetKubeLoginClusterKubeconfigOK) GetPayload() []uint8 {
	return o.Payload
}

func (o *GetKubeLoginClusterKubeconfigOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetKubeLoginClusterKubeconfigUnauthorized creates a GetKubeLoginClusterKubeconfigUnauthorized with default headers values
func NewGetKubeLoginClusterKubeconfigUnauthorized() *GetKubeLoginClusterKubeconfigUnauthorized {
	return &GetKubeLoginClusterKubeconfigUnauthorized{}
}

/*GetKubeLoginClusterKubeconfigUnauthorized handles this case with default header values.

EmptyResponse is a empty response
*/
type GetKubeLoginClusterKubeconfigUnauthorized struct {
}

func (o *GetKubeLoginClusterKubeconfigUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/kubeloginkubeconfig][%d] getKubeLoginClusterKubeconfigUnauthorized ", 401)
}

func (o *GetKubeLoginClusterKubeconfigUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetKubeLoginClusterKubeconfigForbidden creates a GetKubeLoginClusterKubeconfigForbidden with default headers values
func NewGetKubeLoginClusterKubeconfigForbidden() *GetKubeLoginClusterKubeconfigForbidden {
	return &GetKubeLoginClusterKubeconfigForbidden{}
}

/*GetKubeLoginClusterKubeconfigForbidden handles this case with default header values.

EmptyResponse is a empty response
*/
type GetKubeLoginClusterKubeconfigForbidden struct {
}

func (o *GetKubeLoginClusterKubeconfigForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/kubeloginkubeconfig][%d] getKubeLoginClusterKubeconfigForbidden ", 403)
}

func (o *GetKubeLoginClusterKubeconfigForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetKubeLoginClusterKubeconfigDefault creates a GetKubeLoginClusterKubeconfigDefault with default headers values
func NewGetKubeLoginClusterKubeconfigDefault(code int) *GetKubeLoginClusterKubeconfigDefault {
	return &GetKubeLoginClusterKubeconfigDefault{
		_statusCode: code,
	}
}

/*GetKubeLoginClusterKubeconfigDefault handles this case with default header values.

errorResponse
*/
type GetKubeLoginClusterKubeconfigDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// Code gets the status code for the get kube login cluster kubeconfig default response
func (o *GetKubeLoginClusterKubeconfigDefault) Code() int {
	return o._statusCode
}

func (o *GetKubeLoginClusterKubeconfigDefault) Error() string {
	return fmt.Sprintf("[GET /api/v1/projects/{project_id}/dc/{dc}/clusters/{cluster_id}/kubeloginkubeconfig][%d] getKubeLoginClusterKubeconfig default  %+v", o._statusCode, o.Payload)
}

func (o *GetKubeLoginClusterKubeconfigDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *GetKubeLoginClusterKubeconfigDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
