// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPatchNodeDeploymentRequestParams creates a new PatchNodeDeploymentRequestParams object
// with the default values initialized.
func NewPatchNodeDeploymentRequestParams() *PatchNodeDeploymentRequestParams {
	var ()
	return &PatchNodeDeploymentRequestParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchNodeDeploymentRequestParamsWithTimeout creates a new PatchNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchNodeDeploymentRequestParamsWithTimeout(timeout time.Duration) *PatchNodeDeploymentRequestParams {
	var ()
	return &PatchNodeDeploymentRequestParams{

		timeout: timeout,
	}
}

// NewPatchNodeDeploymentRequestParamsWithContext creates a new PatchNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchNodeDeploymentRequestParamsWithContext(ctx context.Context) *PatchNodeDeploymentRequestParams {
	var ()
	return &PatchNodeDeploymentRequestParams{

		Context: ctx,
	}
}

// NewPatchNodeDeploymentRequestParamsWithHTTPClient creates a new PatchNodeDeploymentRequestParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchNodeDeploymentRequestParamsWithHTTPClient(client *http.Client) *PatchNodeDeploymentRequestParams {
	var ()
	return &PatchNodeDeploymentRequestParams{
		HTTPClient: client,
	}
}

/*PatchNodeDeploymentRequestParams contains all the parameters to send to the API endpoint
for the patch node deployment request operation typically these are written to a http.Request
*/
type PatchNodeDeploymentRequestParams struct {

	/*Patch*/
	Patch []uint8
	/*ClusterID*/
	ClusterID string
	/*Dc*/
	DC string
	/*NdrequestID*/
	NdrName string
	/*ProjectID*/
	ProjectID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) WithTimeout(timeout time.Duration) *PatchNodeDeploymentRequestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) WithContext(ctx context.Context) *PatchNodeDeploymentRequestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) WithHTTPClient(client *http.Client) *PatchNodeDeploymentRequestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPatch adds the patch to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) WithPatch(patch []uint8) *PatchNodeDeploymentRequestParams {
	o.SetPatch(patch)
	return o
}

// SetPatch adds the patch to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) SetPatch(patch []uint8) {
	o.Patch = patch
}

// WithClusterID adds the clusterID to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) WithClusterID(clusterID string) *PatchNodeDeploymentRequestParams {
	o.SetClusterID(clusterID)
	return o
}

// SetClusterID adds the clusterId to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) SetClusterID(clusterID string) {
	o.ClusterID = clusterID
}

// WithDC adds the dc to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) WithDC(dc string) *PatchNodeDeploymentRequestParams {
	o.SetDC(dc)
	return o
}

// SetDC adds the dc to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) SetDC(dc string) {
	o.DC = dc
}

// WithNdrName adds the ndrequestID to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) WithNdrName(ndrequestID string) *PatchNodeDeploymentRequestParams {
	o.SetNdrName(ndrequestID)
	return o
}

// SetNdrName adds the ndrequestId to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) SetNdrName(ndrequestID string) {
	o.NdrName = ndrequestID
}

// WithProjectID adds the projectID to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) WithProjectID(projectID string) *PatchNodeDeploymentRequestParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the patch node deployment request params
func (o *PatchNodeDeploymentRequestParams) SetProjectID(projectID string) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchNodeDeploymentRequestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Patch != nil {
		if err := r.SetBodyParam(o.Patch); err != nil {
			return err
		}
	}

	// path param cluster_id
	if err := r.SetPathParam("cluster_id", o.ClusterID); err != nil {
		return err
	}

	// path param dc
	if err := r.SetPathParam("dc", o.DC); err != nil {
		return err
	}

	// path param ndrequest_id
	if err := r.SetPathParam("ndrequest_id", o.NdrName); err != nil {
		return err
	}

	// path param project_id
	if err := r.SetPathParam("project_id", o.ProjectID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
