// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Quotas Quotas is a struct that contains the response of a Quotas query.
//
// swagger:model Quotas
type Quotas struct {

	// FloatingIpQuota Sys11 addition with the amount of used and attached floating ips
	FloatingIPQuota int64 `json:"floatingIpQuota,omitempty"`

	// UsedFloatingIpCount is the floating IP quota
	UsedFloatingIPCount int64 `json:"usedFloatingIpCount,omitempty"`

	// limits
	Limits *Limits `json:"limits,omitempty"`
}

// Validate validates this quotas
func (m *Quotas) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLimits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Quotas) validateLimits(formats strfmt.Registry) error {

	if swag.IsZero(m.Limits) { // not required
		return nil
	}

	if m.Limits != nil {
		if err := m.Limits.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("limits")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Quotas) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Quotas) UnmarshalBinary(b []byte) error {
	var res Quotas
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
